ERROR - 2024-04-06 10:48:43 --> Error connecting to the database: mysqli_sql_exception: Nenhuma ligação pôde ser feita porque o computador de destino
as recusou ativamente in C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'corretora', 3306, '', 0)
#1 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Model.php(243): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\app\Controllers\Ativo.php(14): CodeIgniter\BaseModel->findAll()
#7 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(943): App\Controllers\Ativo->index()
#8 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ativo))
#9 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\jucle\\...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Nenhuma ligação pôde ser feita porque o computador de destino
as recusou ativamente in C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Model.php(243): CodeIgniter\Database\BaseBuilder->get()
#4 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\app\Controllers\Ativo.php(14): CodeIgniter\BaseModel->findAll()
#6 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(943): App\Controllers\Ativo->index()
#7 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ativo))
#8 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\jucle\\...')
#11 {main}
CRITICAL - 2024-04-06 10:48:43 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Nenhuma ligação pôde ser feita porque o computador de destino
as recusou ativamente
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `Ativo`', [], false)
 3 SYSTEMPATH\Model.php(243): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Ativo.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Ativo->index()
 7 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ativo))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\jucle\\Documents\\[02] university\\[02] programacao_web_II\\[02] avaliações\\[03] projecto\\project-root\\public\\index.php')
CRITICAL - 2024-04-06 11:00:00 --> ErrorException: Undefined array key "DataAdmissao"
in APPPATH\Views\corretores\corretores_index.php on line 52.
 1 APPPATH\Views\corretores\corretores_index.php(52): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "DataAdmissao"', 'C:\\Users\\jucle\\Documents\\[02] university\\[02] programacao_web_II\\[02] avaliações\\[03] projecto\\project-root\\app\\Views\\corretores\\corretores_index.php', 52)
 2 SYSTEMPATH\View\View.php(228): include('C:\\Users\\jucle\\Documents\\[02] university\\[02] programacao_web_II\\[02] avaliações\\[03] projecto\\project-root\\app\\Views\\corretores\\corretores_index.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('corretores/corretores_index', [], true)
 5 APPPATH\Controllers\Corretor.php(21): view('corretores/corretores_index', [...])
 6 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Corretor->index()
 7 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Corretor))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\jucle\\Documents\\[02] university\\[02] programacao_web_II\\[02] avaliações\\[03] projecto\\project-root\\public\\index.php')
CRITICAL - 2024-04-06 11:01:26 --> ErrorException: Undefined array key "DataAdmissao"
in APPPATH\Views\corretores\corretores_index.php on line 52.
 1 APPPATH\Views\corretores\corretores_index.php(52): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "DataAdmissao"', 'C:\\Users\\jucle\\Documents\\[02] university\\[02] programacao_web_II\\[02] avaliações\\[03] projecto\\project-root\\app\\Views\\corretores\\corretores_index.php', 52)
 2 SYSTEMPATH\View\View.php(228): include('C:\\Users\\jucle\\Documents\\[02] university\\[02] programacao_web_II\\[02] avaliações\\[03] projecto\\project-root\\app\\Views\\corretores\\corretores_index.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('corretores/corretores_index', [], true)
 5 APPPATH\Controllers\Corretor.php(21): view('corretores/corretores_index', [...])
 6 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Corretor->index()
 7 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Corretor))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\jucle\\Documents\\[02] university\\[02] programacao_web_II\\[02] avaliações\\[03] projecto\\project-root\\public\\index.php')
CRITICAL - 2024-04-06 11:01:31 --> ErrorException: Undefined array key "DataAdmissao"
in APPPATH\Views\corretores\corretores_index.php on line 52.
 1 APPPATH\Views\corretores\corretores_index.php(52): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "DataAdmissao"', 'C:\\Users\\jucle\\Documents\\[02] university\\[02] programacao_web_II\\[02] avaliações\\[03] projecto\\project-root\\app\\Views\\corretores\\corretores_index.php', 52)
 2 SYSTEMPATH\View\View.php(228): include('C:\\Users\\jucle\\Documents\\[02] university\\[02] programacao_web_II\\[02] avaliações\\[03] projecto\\project-root\\app\\Views\\corretores\\corretores_index.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('corretores/corretores_index', [], true)
 5 APPPATH\Controllers\Corretor.php(21): view('corretores/corretores_index', [...])
 6 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Corretor->index()
 7 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Corretor))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\jucle\\Documents\\[02] university\\[02] programacao_web_II\\[02] avaliações\\[03] projecto\\project-root\\public\\index.php')
CRITICAL - 2024-04-06 11:02:40 --> ErrorException: Undefined array key "DataAdmissao"
in APPPATH\Views\corretores\corretores_index.php on line 52.
 1 APPPATH\Views\corretores\corretores_index.php(52): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "DataAdmissao"', 'C:\\Users\\jucle\\Documents\\[02] university\\[02] programacao_web_II\\[02] avaliações\\[03] projecto\\project-root\\app\\Views\\corretores\\corretores_index.php', 52)
 2 SYSTEMPATH\View\View.php(228): include('C:\\Users\\jucle\\Documents\\[02] university\\[02] programacao_web_II\\[02] avaliações\\[03] projecto\\project-root\\app\\Views\\corretores\\corretores_index.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('corretores/corretores_index', [], true)
 5 APPPATH\Controllers\Corretor.php(21): view('corretores/corretores_index', [...])
 6 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Corretor->index()
 7 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Corretor))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\jucle\\Documents\\[02] university\\[02] programacao_web_II\\[02] avaliações\\[03] projecto\\project-root\\public\\index.php')
CRITICAL - 2024-04-06 11:16:06 --> ErrorException: Undefined array key "Firma"
in APPPATH\Views\corretores\corretores_editar.php on line 81.
 1 APPPATH\Views\corretores\corretores_editar.php(81): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "Firma"', 'C:\\Users\\jucle\\Documents\\[02] university\\[02] programacao_web_II\\[02] avaliações\\[03] projecto\\project-root\\app\\Views\\corretores\\corretores_editar.php', 81)
 2 SYSTEMPATH\View\View.php(228): include('C:\\Users\\jucle\\Documents\\[02] university\\[02] programacao_web_II\\[02] avaliações\\[03] projecto\\project-root\\app\\Views\\corretores\\corretores_editar.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('corretores/corretores_editar', [], true)
 5 APPPATH\Controllers\Corretor.php(73): view('corretores/corretores_editar', [...])
 6 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Corretor->editar('2')
 7 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Corretor))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\jucle\\Documents\\[02] university\\[02] programacao_web_II\\[02] avaliações\\[03] projecto\\project-root\\public\\index.php')
CRITICAL - 2024-04-06 11:21:35 --> ErrorException: Maximum execution time of 60 seconds exceeded
in SYSTEMPATH\Database\MySQLi\Connection.php on line 307.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
ERROR - 2024-04-06 11:40:19 --> mysqli_sql_exception: Unknown column 'TaxaJurosDiaria' in 'field list' in C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `Fi...', 0)
#1 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `Fi...')
#2 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `Fi...')
#3 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `Fi...', Array, false)
#4 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Model.php(749): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\app\Controllers\Firma.php(36): CodeIgniter\Model->insert(Array)
#8 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(943): App\Controllers\Firma->novo()
#9 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Firma))
#10 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\jucle\\...')
#13 {main}
CRITICAL - 2024-04-06 11:40:19 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'TaxaJurosDiaria' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `Firma` (`Nome`, `TaxaJurosDiaria`, `Endereco`) VALUES (:Nome:, :TaxaJurosDiaria:, :Endereco:)', [...], false)
 2 SYSTEMPATH\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(749): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Firma.php(36): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Firma->novo()
 7 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Firma))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\jucle\\Documents\\[02] university\\[02] programacao_web_II\\[02] avaliações\\[03] projecto\\project-root\\public\\index.php')
CRITICAL - 2024-04-06 11:40:19 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'TaxaJurosDiaria' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `Firma` (`Nome`, `TaxaJurosDiaria`, `Endereco`) VALUES (\'Firma Central\', \'2\', \'Luanda, Morro Bento\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `Firma` (`Nome`, `TaxaJurosDiaria`, `Endereco`) VALUES (\'Firma Central\', \'2\', \'Luanda, Morro Bento\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `Firma` (`Nome`, `TaxaJurosDiaria`, `Endereco`) VALUES (:Nome:, :TaxaJurosDiaria:, :Endereco:)', [...], false)
 4 SYSTEMPATH\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(749): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Firma.php(36): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Firma->novo()
 9 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Firma))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\jucle\\Documents\\[02] university\\[02] programacao_web_II\\[02] avaliações\\[03] projecto\\project-root\\public\\index.php')
CRITICAL - 2024-04-06 11:40:19 --> [Caused by] mysqli_sql_exception: Unknown column 'TaxaJurosDiaria' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `Firma` (`Nome`, `TaxaJurosDiaria`, `Endereco`) VALUES (\'Firma Central\', \'2\', \'Luanda, Morro Bento\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `Firma` (`Nome`, `TaxaJurosDiaria`, `Endereco`) VALUES (\'Firma Central\', \'2\', \'Luanda, Morro Bento\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `Firma` (`Nome`, `TaxaJurosDiaria`, `Endereco`) VALUES (\'Firma Central\', \'2\', \'Luanda, Morro Bento\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `Firma` (`Nome`, `TaxaJurosDiaria`, `Endereco`) VALUES (:Nome:, :TaxaJurosDiaria:, :Endereco:)', [...], false)
 5 SYSTEMPATH\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(749): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Firma.php(36): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Firma->novo()
10 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Firma))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\jucle\\Documents\\[02] university\\[02] programacao_web_II\\[02] avaliações\\[03] projecto\\project-root\\public\\index.php')
CRITICAL - 2024-04-06 12:10:43 --> Error: Object of class DateTime could not be converted to string
in SYSTEMPATH\Database\Query.php on line 333.
 1 SYSTEMPATH\Database\Query.php(333): strtr('INSERT INTO `Operacao` (`CodigoAtivo`, `Quantidade`, `TipoOperacao`, `ComprovativoPagamento`, `DepositoFeito`, `LevantamentoFeito`, `DataOperacao`) VALUES (:CodigoAtivo:, :Quantidade:, :TipoOperacao:, :ComprovativoPagamento:, :DepositoFeito:, :LevantamentoFeito:, :DataOperacao:)', [...])
 2 SYSTEMPATH\Database\Query.php(308): CodeIgniter\Database\Query->matchNamedBinds('INSERT INTO `Operacao` (`CodigoAtivo`, `Quantidade`, `TipoOperacao`, `ComprovativoPagamento`, `DepositoFeito`, `LevantamentoFeito`, `DataOperacao`) VALUES (:CodigoAtivo:, :Quantidade:, :TipoOperacao:, :ComprovativoPagamento:, :DepositoFeito:, :LevantamentoFeito:, :DataOperacao:)', [...])
 3 SYSTEMPATH\Database\Query.php(159): CodeIgniter\Database\Query->compileBinds()
 4 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\Query->getQuery()
 5 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `Operacao` (`CodigoAtivo`, `Quantidade`, `TipoOperacao`, `ComprovativoPagamento`, `DepositoFeito`, `LevantamentoFeito`, `DataOperacao`) VALUES (:CodigoAtivo:, :Quantidade:, :TipoOperacao:, :ComprovativoPagamento:, :DepositoFeito:, :LevantamentoFeito:, :DataOperacao:)', [...], false)
 6 SYSTEMPATH\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
 7 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 8 SYSTEMPATH\Model.php(749): CodeIgniter\BaseModel->insert([...], true)
 9 APPPATH\Controllers\Operacao.php(41): CodeIgniter\Model->insert([...])
10 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Operacao->novo()
11 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Operacao))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\jucle\\Documents\\[02] university\\[02] programacao_web_II\\[02] avaliações\\[03] projecto\\project-root\\public\\index.php')
ERROR - 2024-04-06 12:11:52 --> mysqli_sql_exception: Unknown column 'LevantamentoFeito' in 'field list' in C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `Op...', 0)
#1 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `Op...')
#2 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `Op...')
#3 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `Op...', Array, false)
#4 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Model.php(749): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\app\Controllers\Operacao.php(40): CodeIgniter\Model->insert(Array)
#8 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(943): App\Controllers\Operacao->novo()
#9 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Operacao))
#10 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\jucle\\...')
#13 {main}
CRITICAL - 2024-04-06 12:11:52 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'LevantamentoFeito' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `Operacao` (`CodigoAtivo`, `Quantidade`, `TipoOperacao`, `ComprovativoPagamento`, `DepositoFeito`, `LevantamentoFeito`) VALUES (:CodigoAtivo:, :Quantidade:, :TipoOperacao:, :ComprovativoPagamento:, :DepositoFeito:, :LevantamentoFeito:)', [...], false)
 2 SYSTEMPATH\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(749): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Operacao.php(40): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Operacao->novo()
 7 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Operacao))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\jucle\\Documents\\[02] university\\[02] programacao_web_II\\[02] avaliações\\[03] projecto\\project-root\\public\\index.php')
CRITICAL - 2024-04-06 12:11:52 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'LevantamentoFeito' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `Operacao` (`CodigoAtivo`, `Quantidade`, `TipoOperacao`, `ComprovativoPagamento`, `DepositoFeito`, `LevantamentoFeito`) VALUES (\'Alaska\', \'12333\', \'Compra\', \'[01] budget.xlsx\', \'on\', \'on\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `Operacao` (`CodigoAtivo`, `Quantidade`, `TipoOperacao`, `ComprovativoPagamento`, `DepositoFeito`, `LevantamentoFeito`) VALUES (\'Alaska\', \'12333\', \'Compra\', \'[01] budget.xlsx\', \'on\', \'on\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `Operacao` (`CodigoAtivo`, `Quantidade`, `TipoOperacao`, `ComprovativoPagamento`, `DepositoFeito`, `LevantamentoFeito`) VALUES (:CodigoAtivo:, :Quantidade:, :TipoOperacao:, :ComprovativoPagamento:, :DepositoFeito:, :LevantamentoFeito:)', [...], false)
 4 SYSTEMPATH\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(749): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Operacao.php(40): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Operacao->novo()
 9 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Operacao))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\jucle\\Documents\\[02] university\\[02] programacao_web_II\\[02] avaliações\\[03] projecto\\project-root\\public\\index.php')
CRITICAL - 2024-04-06 12:11:52 --> [Caused by] mysqli_sql_exception: Unknown column 'LevantamentoFeito' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `Operacao` (`CodigoAtivo`, `Quantidade`, `TipoOperacao`, `ComprovativoPagamento`, `DepositoFeito`, `LevantamentoFeito`) VALUES (\'Alaska\', \'12333\', \'Compra\', \'[01] budget.xlsx\', \'on\', \'on\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `Operacao` (`CodigoAtivo`, `Quantidade`, `TipoOperacao`, `ComprovativoPagamento`, `DepositoFeito`, `LevantamentoFeito`) VALUES (\'Alaska\', \'12333\', \'Compra\', \'[01] budget.xlsx\', \'on\', \'on\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `Operacao` (`CodigoAtivo`, `Quantidade`, `TipoOperacao`, `ComprovativoPagamento`, `DepositoFeito`, `LevantamentoFeito`) VALUES (\'Alaska\', \'12333\', \'Compra\', \'[01] budget.xlsx\', \'on\', \'on\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `Operacao` (`CodigoAtivo`, `Quantidade`, `TipoOperacao`, `ComprovativoPagamento`, `DepositoFeito`, `LevantamentoFeito`) VALUES (:CodigoAtivo:, :Quantidade:, :TipoOperacao:, :ComprovativoPagamento:, :DepositoFeito:, :LevantamentoFeito:)', [...], false)
 5 SYSTEMPATH\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(749): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Operacao.php(40): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Operacao->novo()
10 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Operacao))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\jucle\\Documents\\[02] university\\[02] programacao_web_II\\[02] avaliações\\[03] projecto\\project-root\\public\\index.php')
ERROR - 2024-04-06 12:12:30 --> mysqli_sql_exception: Unknown column 'LevantamentoFeito' in 'field list' in C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `Op...', 0)
#1 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `Op...')
#2 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `Op...')
#3 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `Op...', Array, false)
#4 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Model.php(749): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\app\Controllers\Operacao.php(41): CodeIgniter\Model->insert(Array)
#8 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(943): App\Controllers\Operacao->novo()
#9 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Operacao))
#10 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\jucle\\...')
#13 {main}
CRITICAL - 2024-04-06 12:12:30 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'LevantamentoFeito' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `Operacao` (`CodigoAtivo`, `Quantidade`, `TipoOperacao`, `ComprovativoPagamento`, `DepositoFeito`, `LevantamentoFeito`) VALUES (:CodigoAtivo:, :Quantidade:, :TipoOperacao:, :ComprovativoPagamento:, :DepositoFeito:, :LevantamentoFeito:)', [...], false)
 2 SYSTEMPATH\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(749): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Operacao.php(41): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Operacao->novo()
 7 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Operacao))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\jucle\\Documents\\[02] university\\[02] programacao_web_II\\[02] avaliações\\[03] projecto\\project-root\\public\\index.php')
CRITICAL - 2024-04-06 12:12:30 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'LevantamentoFeito' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `Operacao` (`CodigoAtivo`, `Quantidade`, `TipoOperacao`, `ComprovativoPagamento`, `DepositoFeito`, `LevantamentoFeito`) VALUES (\'Alaska\', \'12333\', \'Compra\', \'[01] budget.xlsx\', \'on\', \'on\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `Operacao` (`CodigoAtivo`, `Quantidade`, `TipoOperacao`, `ComprovativoPagamento`, `DepositoFeito`, `LevantamentoFeito`) VALUES (\'Alaska\', \'12333\', \'Compra\', \'[01] budget.xlsx\', \'on\', \'on\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `Operacao` (`CodigoAtivo`, `Quantidade`, `TipoOperacao`, `ComprovativoPagamento`, `DepositoFeito`, `LevantamentoFeito`) VALUES (:CodigoAtivo:, :Quantidade:, :TipoOperacao:, :ComprovativoPagamento:, :DepositoFeito:, :LevantamentoFeito:)', [...], false)
 4 SYSTEMPATH\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(749): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Operacao.php(41): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Operacao->novo()
 9 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Operacao))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\jucle\\Documents\\[02] university\\[02] programacao_web_II\\[02] avaliações\\[03] projecto\\project-root\\public\\index.php')
CRITICAL - 2024-04-06 12:12:30 --> [Caused by] mysqli_sql_exception: Unknown column 'LevantamentoFeito' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `Operacao` (`CodigoAtivo`, `Quantidade`, `TipoOperacao`, `ComprovativoPagamento`, `DepositoFeito`, `LevantamentoFeito`) VALUES (\'Alaska\', \'12333\', \'Compra\', \'[01] budget.xlsx\', \'on\', \'on\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `Operacao` (`CodigoAtivo`, `Quantidade`, `TipoOperacao`, `ComprovativoPagamento`, `DepositoFeito`, `LevantamentoFeito`) VALUES (\'Alaska\', \'12333\', \'Compra\', \'[01] budget.xlsx\', \'on\', \'on\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `Operacao` (`CodigoAtivo`, `Quantidade`, `TipoOperacao`, `ComprovativoPagamento`, `DepositoFeito`, `LevantamentoFeito`) VALUES (\'Alaska\', \'12333\', \'Compra\', \'[01] budget.xlsx\', \'on\', \'on\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `Operacao` (`CodigoAtivo`, `Quantidade`, `TipoOperacao`, `ComprovativoPagamento`, `DepositoFeito`, `LevantamentoFeito`) VALUES (:CodigoAtivo:, :Quantidade:, :TipoOperacao:, :ComprovativoPagamento:, :DepositoFeito:, :LevantamentoFeito:)', [...], false)
 5 SYSTEMPATH\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(749): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Operacao.php(41): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Operacao->novo()
10 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Operacao))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\jucle\\Documents\\[02] university\\[02] programacao_web_II\\[02] avaliações\\[03] projecto\\project-root\\public\\index.php')
CRITICAL - 2024-04-06 12:18:28 --> ErrorException: Undefined variable $operacoes
in APPPATH\Views\operacoes\operacoes_detalhes.php on line 36.
 1 APPPATH\Views\operacoes\operacoes_detalhes.php(36): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $operacoes', 'C:\\Users\\jucle\\Documents\\[02] university\\[02] programacao_web_II\\[02] avaliações\\[03] projecto\\project-root\\app\\Views\\operacoes\\operacoes_detalhes.php', 36)
 2 SYSTEMPATH\View\View.php(228): include('C:\\Users\\jucle\\Documents\\[02] university\\[02] programacao_web_II\\[02] avaliações\\[03] projecto\\project-root\\app\\Views\\operacoes\\operacoes_detalhes.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('operacoes/operacoes_detalhes', [], true)
 5 APPPATH\Controllers\Operacao.php(57): view('operacoes/operacoes_detalhes', [...])
 6 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Operacao->detalhes('1')
 7 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Operacao))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\jucle\\Documents\\[02] university\\[02] programacao_web_II\\[02] avaliações\\[03] projecto\\project-root\\public\\index.php')
CRITICAL - 2024-04-06 12:36:27 --> ErrorException: Undefined array key "password"
in APPPATH\Models\UsuarioModel.php on line 18.
 1 APPPATH\Models\UsuarioModel.php(18): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "password"', 'C:\\Users\\jucle\\Documents\\[02] university\\[02] programacao_web_II\\[02] avaliações\\[03] projecto\\project-root\\app\\Models\\UsuarioModel.php', 18)
 2 SYSTEMPATH\BaseModel.php(1646): App\Models\UsuarioModel->hashPassword([...])
 3 SYSTEMPATH\BaseModel.php(799): CodeIgniter\BaseModel->trigger('beforeInsert', [...])
 4 SYSTEMPATH\Model.php(749): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Usuario.php(37): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Usuario->novo()
 7 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuario))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\jucle\\Documents\\[02] university\\[02] programacao_web_II\\[02] avaliações\\[03] projecto\\project-root\\public\\index.php')
CRITICAL - 2024-04-06 13:26:55 --> ErrorException: Undefined variable $usuario
in APPPATH\Views\carteiras\carteiras_editar.php on line 47.
 1 APPPATH\Views\carteiras\carteiras_editar.php(47): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $usuario', 'C:\\Users\\jucle\\Documents\\[02] university\\[02] programacao_web_II\\[02] avaliações\\[03] projecto\\project-root\\app\\Views\\carteiras\\carteiras_editar.php', 47)
 2 SYSTEMPATH\View\View.php(228): include('C:\\Users\\jucle\\Documents\\[02] university\\[02] programacao_web_II\\[02] avaliações\\[03] projecto\\project-root\\app\\Views\\carteiras\\carteiras_editar.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('carteiras/carteiras_editar', [], true)
 5 APPPATH\Controllers\Carteira.php(48): view('carteiras/carteiras_editar', [...])
 6 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Carteira->editar('1')
 7 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Carteira))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\jucle\\Documents\\[02] university\\[02] programacao_web_II\\[02] avaliações\\[03] projecto\\project-root\\public\\index.php')
CRITICAL - 2024-04-06 13:37:02 --> ErrorException: Undefined array key "NomeComleto"
in APPPATH\Views\autenticacao\perfil.php on line 53.
 1 APPPATH\Views\autenticacao\perfil.php(53): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "NomeComleto"', 'C:\\Users\\jucle\\Documents\\[02] university\\[02] programacao_web_II\\[02] avaliações\\[03] projecto\\project-root\\app\\Views\\autenticacao\\perfil.php', 53)
 2 SYSTEMPATH\View\View.php(228): include('C:\\Users\\jucle\\Documents\\[02] university\\[02] programacao_web_II\\[02] avaliações\\[03] projecto\\project-root\\app\\Views\\autenticacao\\perfil.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('autenticacao/perfil', [], true)
 5 APPPATH\Controllers\Autenticacao.php(64): view('autenticacao/perfil', [...])
 6 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Autenticacao->perfil()
 7 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Autenticacao))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\jucle\\Documents\\[02] university\\[02] programacao_web_II\\[02] avaliações\\[03] projecto\\project-root\\public\\index.php')
ERROR - 2024-04-06 14:31:46 --> Error connecting to the database: mysqli_sql_exception: Nenhuma ligação pôde ser feita porque o computador de destino
as recusou ativamente in C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'corretora', 3306, '', 0)
#1 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Model.php(243): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\app\Controllers\Home.php(15): CodeIgniter\BaseModel->findAll()
#7 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(943): App\Controllers\Home->index()
#8 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\jucle\\...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Nenhuma ligação pôde ser feita porque o computador de destino
as recusou ativamente in C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Model.php(243): CodeIgniter\Database\BaseBuilder->get()
#4 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\app\Controllers\Home.php(15): CodeIgniter\BaseModel->findAll()
#6 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(943): App\Controllers\Home->index()
#7 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\Users\jucle\Documents\[02] university\[02] programacao_web_II\[02] avaliações\[03] projecto\project-root\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\Users\\jucle\\...')
#11 {main}
CRITICAL - 2024-04-06 14:31:46 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Nenhuma ligação pôde ser feita porque o computador de destino
as recusou ativamente
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `Ativo`', [], false)
 3 SYSTEMPATH\Model.php(243): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Home.php(15): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Home->index()
 7 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\jucle\\Documents\\[02] university\\[02] programacao_web_II\\[02] avaliações\\[03] projecto\\project-root\\public\\index.php')
CRITICAL - 2024-04-06 14:32:05 --> Error: Undefined constant "App\Controllers\totalAtivos"
in APPPATH\Controllers\Home.php on line 21.
 1 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Home->index()
 2 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\jucle\\Documents\\[02] university\\[02] programacao_web_II\\[02] avaliações\\[03] projecto\\project-root\\public\\index.php')
CRITICAL - 2024-04-06 14:32:27 --> CodeIgniter\Database\Exceptions\DataException: Empty statement is given for the field "Select"
in SYSTEMPATH\Database\BaseBuilder.php on line 511.
 1 SYSTEMPATH\Database\BaseBuilder.php(511): CodeIgniter\Database\Exceptions\DataException::forEmptyInputGiven('Select')
 2 SYSTEMPATH\Database\BaseBuilder.php(482): CodeIgniter\Database\BaseBuilder->maxMinAvgSum('', '', 'COUNT')
 3 SYSTEMPATH\Model.php(877): CodeIgniter\Database\BaseBuilder->selectCount()
 4 APPPATH\Controllers\Home.php(21): CodeIgniter\Model->__call('selectCount', [])
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\Users\\jucle\\Documents\\[02] university\\[02] programacao_web_II\\[02] avaliações\\[03] projecto\\project-root\\public\\index.php')
